/**
 * Ambient declarations for the virtual modules generated by
 * electron-ipc-auto-import. Reference once in your project, e.g. in an
 * `env.d.ts`:
 *
 *   /// <reference types="electron-ipc-auto-import/client" />
 */

declare module 'virtual:electron-ipc/main' {
  export interface RegisterIpcHandlersOptions {
    eventArg?: boolean
    validate?: (channel: string, args: unknown[]) => unknown[] | void
    serializeError?: (err: unknown) => unknown
  }
  /** Register every discovered handler with ipcMain. Idempotent per channel. */
  export function registerIpcHandlers(
    overrides?: RegisterIpcHandlersOptions,
  ): void
  export default registerIpcHandlers
}

declare module 'virtual:electron-ipc/preload' {
  /** The contextBridge api object (also exposed on window via the side effect). */
  const api: unknown
  export default api
  /** All channels exposed by this bridge (structural allowlist). */
  export const channels: string[]
}
