import { resolve } from 'node:path'
import { app, BrowserWindow } from 'electron'
// Virtual module generated by electron-ipc-auto-import: registers every
// discovered handler with ipcMain.
import { registerIpcHandlers } from 'virtual:electron-ipc/main'

function createWindow(): void {
  const win = new BrowserWindow({
    width: 900,
    height: 640,
    webPreferences: {
      preload: resolve(__dirname, '../preload/index.js'),
      contextIsolation: true,
      sandbox: true,
      nodeIntegration: false,
    },
  })

  win.loadFile(resolve(__dirname, '../renderer/index.html'))
}

app.whenReady().then(() => {
  registerIpcHandlers()
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
