import path from 'node:path'
import type { HandlerEntry, HandlerManifest, ResolvedOptions } from '../../types'
import { buildTree, type NsNode } from './tree'
import { isIdentifier, relativeSpecifier, singleQuote, toPosix } from '../utils'

/**
 * Generate the physical `.d.ts` that types `window.<bridge>`.
 *
 * Renderer types reference the main-process source signatures via type-only
 * `typeof import(...)`, so they stay in sync automatically and are erased at
 * compile time (never pulling main code into the renderer bundle).
 */
export function generateDts(
  manifest: HandlerManifest,
  options: ResolvedOptions,
): string {
  if (options.dts === false) return ''

  const dtsPath = options.dts
  const root = buildTree(manifest)
  const body = renderNode(root, 1, dtsPath, options)

  const helpers =
    `type _Awaited<T> = T extends Promise<infer U> ? U : T\n` +
    `type _Fn = (...args: any[]) => any\n` +
    (options.eventArg
      ? // Drop the IpcMainInvokeEvent first parameter from the renderer signature.
        `type _Tail<T extends any[]> = T extends [any, ...infer R] ? R : []\n` +
        `type _Invoke<F extends _Fn> = (...args: _Tail<Parameters<F>>) => Promise<_Awaited<ReturnType<F>>>\n`
      : `type _Invoke<F extends _Fn> = (...args: Parameters<F>) => Promise<_Awaited<ReturnType<F>>>\n`)

  return `// Generated by electron-ipc-auto-import. Do not edit.
/* eslint-disable */
// @ts-nocheck
${helpers}
export interface IpcApi ${body}

declare global {
  interface Window {
    ${propKey(options.bridgeName)}: IpcApi
  }
}

export {}
`
}

function renderNode(
  node: NsNode,
  depth: number,
  dtsPath: string,
  options: ResolvedOptions,
): string {
  const indent = '  '.repeat(depth)
  const childIndent = '  '.repeat(depth + 1)
  const lines: string[] = []

  for (const [name, entry] of node.methods) {
    if (entry.jsDoc) lines.push(renderJsDoc(entry.jsDoc, childIndent))
    const spec = moduleSpecifier(entry, dtsPath, options)
    const member = `typeof import(${singleQuote(spec)})[${singleQuote(entry.exportName)}]`
    lines.push(`${childIndent}${propKey(name)}: _Invoke<${member}>`)
  }
  for (const [name, child] of node.namespaces) {
    lines.push(`${childIndent}${propKey(name)}: ${renderNode(child, depth + 1, dtsPath, options)}`)
  }

  if (lines.length === 0) return '{}'
  return `{\n${lines.join('\n')}\n${indent}}`
}

function moduleSpecifier(
  entry: HandlerEntry,
  dtsPath: string,
  options: ResolvedOptions,
): string {
  if (options.pathStyle === 'absolute') return entry.importPath
  if (options.pathStyle === 'alias') {
    // Best-effort: emit a root-relative specifier the user can map via tsconfig paths.
    const rel = toPosix(path.relative(options.root, entry.importPath))
    return `~/${rel}`
  }
  return relativeSpecifier(dtsPath, entry.importPath)
}

function renderJsDoc(text: string, indent: string): string {
  const lines = text.split('\n').map((l) => `${indent} * ${l}`.trimEnd())
  return `${indent}/**\n${lines.join('\n')}\n${indent} */`
}

function propKey(name: string): string {
  return isIdentifier(name) ? name : singleQuote(name)
}
