import type { HandlerManifest, ResolvedOptions } from '../../types'
import { singleQuote } from '../utils'

/**
 * Generate the source of the `virtual:electron-ipc/main` module.
 *
 * Imports each handler module by absolute path and hands a flat channel→handler
 * list to the runtime `registerHandlers`. The user calls `registerIpcHandlers()`
 * once, after `app.whenReady()`.
 */
export function generateMainModule(
  manifest: HandlerManifest,
  options: ResolvedOptions,
): string {
  // One namespaced import per unique module.
  const moduleAlias = new Map<string, string>()
  for (const entry of manifest) {
    if (!moduleAlias.has(entry.importPath)) {
      moduleAlias.set(entry.importPath, `_m${moduleAlias.size}`)
    }
  }

  const imports = [...moduleAlias].map(
    ([importPath, alias]) =>
      `import * as ${alias} from ${singleQuote(importPath)}`,
  )

  const handlers = manifest.map((entry) => {
    const alias = moduleAlias.get(entry.importPath)!
    return `  { channel: ${singleQuote(entry.channel)}, handler: ${alias}[${singleQuote(entry.exportName)}] },`
  })

  return `// Generated by electron-ipc-auto-import. Do not edit.
import { registerHandlers } from 'electron-ipc-auto-import/runtime/main'
${imports.join('\n')}

const __handlers = [
${handlers.join('\n')}
]

const __baseOptions = { eventArg: ${options.eventArg} }

/**
 * Register all discovered IPC handlers with ipcMain. Idempotent: calling more
 * than once is a no-op for already-registered channels.
 */
export function registerIpcHandlers(overrides) {
  return registerHandlers(__handlers, { ...__baseOptions, ...overrides })
}

export default registerIpcHandlers
`
}
