import type { HandlerManifest, ResolvedOptions } from '../../types'
import { buildTree, type NsNode } from './tree'
import { isIdentifier, singleQuote } from '../utils'

/**
 * Generate the source of the `virtual:electron-ipc/preload` module.
 *
 * Built purely from runtime channel strings (no main-source import). Each method
 * is an invoker closing over a literal channel — the renderer can never invoke
 * an arbitrary channel. The assembled object is frozen and exposed via
 * contextBridge.
 */
export function generatePreloadModule(
  manifest: HandlerManifest,
  options: ResolvedOptions,
): string {
  const root = buildTree(manifest)
  const channels = manifest.map((e) => singleQuote(e.channel))
  const apiLiteral = renderNode(root, 1)

  return `// Generated by electron-ipc-auto-import. Do not edit.
import { contextBridge } from 'electron'
import { createInvoker, freezeDeep } from 'electron-ipc-auto-import/runtime/preload'

/** All channels exposed by this bridge (structural allowlist). */
export const channels = [
${channels.map((c) => `  ${c},`).join('\n')}
]

const api = freezeDeep(${apiLiteral})

contextBridge.exposeInMainWorld(${singleQuote(options.bridgeName)}, api)

export default api
`
}

function renderNode(node: NsNode, depth: number): string {
  const indent = '  '.repeat(depth)
  const childIndent = '  '.repeat(depth + 1)
  const lines: string[] = []

  for (const [name, entry] of node.methods) {
    lines.push(`${childIndent}${key(name)}: createInvoker(${singleQuote(entry.channel)}),`)
  }
  for (const [name, child] of node.namespaces) {
    lines.push(`${childIndent}${key(name)}: ${renderNode(child, depth + 1)},`)
  }

  if (lines.length === 0) return '{}'
  return `{\n${lines.join('\n')}\n${indent}}`
}

function key(name: string): string {
  return isIdentifier(name) ? name : singleQuote(name)
}
